Alertの実装
Yuseidosukoiya/Yusei-frontend-basic-2022-todoapp-2 pull request #13
Opened 2024-02-07 04:37 UTC by Yuseidosukoiya

すいません、見た目上は全くうまく動いていないんですけど、理由がわからないので宜しくお願いします。

2024-02-07 12:23 UTC, Riku-Obata requested changes
コメントしました！　確認をお願いします。

2024-02-07 12:23 UTC, Riku-Obata commented on src/components/Atoms/Alert/index.jsx
> +  opacity: ${(isActive) => (isActive ? 1 : 0)};
```suggestion
 opacity:0;
  ${(props) =>
    props.isActive &&
    `{opacity:1 ; transform: translateX(-50%) translateY(0)}`};
```
このように書くことで、フェードイン・アウトが出来ます。
&& は論理積といいます。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_AND

![スクリーンショット (55)](https://github.com/Yuseidosukoiya/Yusei-frontend-basic-2022-todoapp-2/assets/137466167/f937d31e-ba7e-4394-9cc0-6a9c299857b7)
教科書の例ではCSSプロパティは｛｝の外にありますが、中に書くこともできます。

2024-02-07 12:23 UTC, Riku-Obata commented on src/components/Atoms/Alert/index.jsx
> +  transform: translateX(-50%);
```suggestion
  transform: translateX(-50%) translateY(-40px);
```
translateY(-40px) がないと、フェードイン・アウトが出来ません。

2024-02-07 12:23 UTC, Riku-Obata commented on src/components/Atoms/Input/index.jsx
３行目　import { useAlertHandlerContext } from "../../../contexts/alert_handler";
10行目　const AlertHandlerContext = useAlertHandlerContext();
18行目　AlertHandlerContext.setAlert("タスクの名前が設定されていません。");

以上は Atoms/Input ではなく、Organisms/TodoCard に書いてください。

2024-02-07 12:23 UTC, Riku-Obata commented on src/components/Atoms/Alert/index.stories.jsx
> +export const Default = {};
```suggestion
export const Default = {
　args: {
    　isActive: true,
    　errorText: "text",
 　 },
  };
```
StoryBookに表示させるためには、この記述が必要です。

2024-02-07 12:23 UTC, Riku-Obata commented on src/components/Organisms/AlertManager/index.jsx
> +        AlertHandlerContext.closeArelt();
```suggestion
        AlertHandlerContext.closeAlert();
```
スペルミスだと思います。

2024-02-08 10:39 UTC, Riku-Obata requested changes
再コメントしました！　修正のほうをお願いします。
コース修了まであと少しなので、頑張ってください！

2024-02-08 10:39 UTC, Riku-Obata commented on src/components/Atoms/Alert/index.jsx
> +  height: 20px;
ここのheightは削除してください。

2024-02-08 10:39 UTC, Riku-Obata commented on src/components/Atoms/Alert/index.jsx
> +  transform: translateX(-50%);
29行目に同じコードがあるので、削除してもいいと思います。

2024-02-08 10:39 UTC, Riku-Obata commented on src/components/Organisms/ToDoCard/index.jsx
> +      AlertHandlerContext.setAlert("タスクの名前が設定されていません。");
```suggestion
     const filteredOnTaskNameChange = taskList.filter(
        (_, idx) => idx !== index
      );
      setTaskList(filteredOnTaskNameChange);
      AlertHandlerContext.setAlert("タスクの名前が設定されていません。");
```
文字を何も入力しないとき、写真のようになっていたので修正をお願いします。
![スクリーンショット (56)](https://github.com/Yuseidosukoiya/Yusei-frontend-basic-2022-todoapp-2/assets/137466167/0d610a3a-2624-4ef8-87fd-315b551623f6)

filterの使い方は、以下の参考サイトを見てください！
https://qiita.com/itachi/items/4184b2afc35b55b45568
https://jsnotice.com/posts/2020-07-19/index.html

2024-02-08 10:39 UTC, Riku-Obata commented on src/components/Organisms/ToDoCard/index.jsx
>        modifiedTaskList[index].initializing = false;
４４行目の setTaskList(modifiedTaskList); をelseの中に入れてみてください
このままだと、空文字なのにアラートが表示されてしまいます。

![スクリーンショット (57)](https://github.com/Yuseidosukoiya/Yusei-frontend-basic-2022-todoapp-2/assets/137466167/d06d1bb6-db43-446a-9303-95a218c23e3f)

2024-02-08 10:39 UTC, Riku-Obata commented on src/contexts/alert_handler.jsx
> +    setAlertState[modifiedAlertState];
ここも同様に修正をお願いします。

2024-02-08 10:44 UTC, Riku-Obata requested changes

2024-02-08 10:44 UTC, Riku-Obata commented on src/contexts/alert_handler.jsx
> +    setAlertState[modifiedAlertState];
```
    const modifiedAlertState = alertState;
    modifiedAlertState.errorText = errorText;
    modifiedAlertState.visible = true;
    setAlertState[modifiedAlertState];
```
ここのコード、しっかり考えられて凄いと思いましたが、これだとアラートの表示が出来ないみたいです。25～27行目のコードがヒントとなっているので修正をお願いします。

補助教材のヒントです
https://shinonome-inc.notion.site/React-5fbd13e5bfad4eb0b93e666d127662d9

2024-02-08 15:47 UTC, Riku-Obata commented
きちんと修正されていて、いいと思います！

2024-02-09 06:31 UTC, ssshun3 approved these changes
LGTMです。お疲れ様でした、コース課題修了です。
全体を通してみて提出ペースも速く修正も、とても速くてGOODでした。
今後の活躍を期待しています

2024-02-09 06:50 UTC, merged